version: '3.7'
services:

  frontend:
    image: frontend
    ports:
      - "8081:80"

  backend:
    build: .
    container_name: backend
    links:
      - mysql
    volumes:
      - ./backend/src:/var/www/html/
    ports:
      - "8082:80"
 
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    image: mysql
    restart: always
    volumes:
         - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
         MYSQL_ROOT_PASSWORD: admin
         MYSQL_DATABASE: Forum_User
         MYSQL_USER: admin
         MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"